'''
Constants
'''
# Reference String Limits
REF_STRING_MAX_VALUE = 50;
REF_STRING_DEFAULT_VALUE = 15;
REF_STRING_MIN_VALUE = 4;
# Frames Limit
FRAMES_MAX_VALUE = 12;
FRAMES_DEFAULT_VALUE = 4;
FRAMES_MIN_VALUE = 2;